[book]
authors = ["The QuillSQL Team"]
language = "en"
src = "src"
title = "QuillSQL Internals"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
site-url = "/QuillSQL/"

additional-js = ["mermaid.min.js", "mermaid-init.js"]
